### ISSUE TITLE
App Crash - Attempt to use history.pushState() more than 100 time per 30 seconds

### ISSUE THREAD

**Issue by danhollick** [ardov/huetone#1]
Hey @ardov 

I keep hitting this bug:
Adjusting a color a lot in a short period via the HCL graphs can cause the app to crash and give the following error:

```
SecurityError: Attempt to use history.pushState() more than 100 times per 30 seconds
```
It also happens when using the keyboard shortcuts.

Browser: Safari
Video:
https://user-images.githubusercontent.com/13898607/149143837-9db2b664-1597-4f65-a7d1-7dadb1e11756.mov

**Comment by ardov** [comment]
Fixed in #4 which is deployed now
