### ISSUE TITLE
Add P3 and Rec2020 support

### ISSUE THREAD

**Issue by ai** [ardov/huetone#2]
Thanks for amazing tool. I love it so much and use to rgb → lch convert.

Now we start to work with P3 colors and found that tool is not very useful. We can send PR to improve P3 support, but want to got a approve from maintainer first.

My current plans:

1. I see only one border on canvases right now. It seems like it is a border for sRGB colors. We want to add multiple borders for sRGB limit, P3 limit, Rec2020 limit and eye visibility limit.
2. In additional to making RGB hex field red, add a note that color is out of sRGB or is out of P3 color space.
3. Optionally we can hide Rec2020 limit and show it only by hot key (since we do not have enough Rec2020 screens right now).

![image](https://user-images.githubusercontent.com/19343/149947137-e42bb8d8-1acf-40d4-bd7e-793cd6e4cf1f.png)

I think it will be very useful changes for the tool because we have a lot P3 displays right now (most of OLED screens, all modern Apple screens), Safari got a full support for P3 colors and other browsers and CSSWG is planning to add this support too.

**Comment by ardov** [comment]
Sounds like a good addition 👍
I'd make wider gamuts optional they are still a pretty new thing.

If your PR is not ready yet I'd ask you to wait a couple of days. Currently I'm working on adding OKLCH color space and have a lot of stuff broken inside. I plan to release the new version with lots of inner changes this weekend

**Comment by ai** [comment]
Cool. I will wait for release before creating a task for PR.

**Comment by ai** [comment]
It looks amazing 🤩

When you plan to deploy it? I want to promote this feature in Twitter.

**Comment by ardov** [comment]
Glad you like it. Hope to release this thursday or friday. There is still a list of improvements to make 🥴

**Comment by ardov** [comment]
The new version is just deployed 😉
So, closing this issue.
