### ISSUE TITLE
Add Auto value to theme switcher

### ISSUE THREAD

**Issue by ai** [ardov/huetone#3]
Now switcher has only Sun and Moon icon for light and dark theme.

It is not obvious how to set Auto mode to use system default (which is the best mode for modern OS since they all have sunset/sunrise theme switching).

I try to read sources, but was not lucky to understand the logic.

What do you think of adding `A` mode, which will be default?

**Comment by ardov** [comment]
Hi, Andrey! Huetone takes a pretty experimental approach to theme switching. I'm still playing with it.

Here are the assumptions on which it is based:
- Users think in terms of light/dark theme and don't even need to know about the system theme.
- Users switch themes when they don't like the current one.

So, of course, by default Huetone respects the system theme and adapts.
But when switching the theme, a rather tricky logic works under the hood. If the user wants a theme that matches the system one, the system one will be chosen. But if the user, on the contrary, does not want the system one, then Huetone will remember the choice.

It's definitely may not seem obvious. But in real scenarios it works well and I like the simplicity on the surface.

**Comment by ai** [comment]
> But when switching the theme, a rather tricky logic works under the hood. If the user wants a theme that matches the system one, the system one will be chosen.

I was not able to make it switch back to system theme. I switched it back to light theme when my OS was in light theme but now (in dark theme) it is still locked in light theme?

Is it a bug?

> It's definitely may not seem obvious. But in real scenarios it works well and I like the simplicity on the surface.

Do you think that simpler UX is better since it requires less code and more obvious for users?

We just need `A` icon.

**Comment by ardov** [comment]
> I switched it back to light theme when my OS was in light theme but now (in dark theme) it is still locked in light theme

That seems like a bug, but I couldn't reproduce it. Is it reproducible for you?

Speaking of UX, I think that UI should be simple and reflect the user mental model. And none of this related with the amount of code.
Anyway at this moment I think that 2 states works better than 3. The same logic works on my other project for a year now and there was no negative feedback from real users. But, of course, I may change my mind later 🙂

**Comment by ai** [comment]
> That seems like a bug, but I couldn't reproduce it. Is it reproducible for you?

I tried more careful with the instruction from you and seems like I was able to revert it back to system

**Comment by ardov** [comment]
Theme switch that needs instruction definitely isn't a good sign 😆
Projects like this is a good playground for me to test that kind of crazy ideas and receive feedback. Thank you for this issue!
