### ISSUE TITLE
Add a way to copy `lch()` color

### ISSUE THREAD

**Issue by ai** [ardov/huetone#5]
`lch(47% 74 33)` color notion is coming to CSS and can be used today with PostCSS polyfills.

I think it could be a very useful to be able to copy `lch()` from your awesome tool since you already have L, C, H values in URL. Right now, I copy number by number, but it will be nice to be able to copy `lch()` notation in one or two clicks.

My favorite way would be to have `copy` icon with `Copy lch()` tooltip. But I think a shortcut or a value in a dropdown menu is also an option.

**Comment by ardov** [comment]
Yep, want to add a panel with information about the color and it will be a good addition.
Btw, also thought about a hotkey for it. Currently `⌘`+`C` copies hex value of selected color, but I can add `Shift`+`⌘`+`C` to copy it in raw `lch()` format. What do you think about it?

**Comment by ai** [comment]
> I can add Shift+⌘+C to copy it in raw lch() format. What do you think about it?

Looks great for me.

If we have a note about this shortcut in the help section below, it will cover my needs completely.

**Comment by ardov** [comment]
Great! Just added `Shift`+`⌘`+`C` shortcut, so closing it

**Comment by ai** [comment]
> only supported by Safari

It is very limited user set 😥 (I use Linux and Firefox).

Why do we have this limit?

**Comment by ardov** [comment]
Oh, it's a comment about browser support for `lch()` notation. Shortcut should work everywhere 😀

**Comment by ai** [comment]
Should we make text more clear? For instance something like `lch() has limited [browser support]` with link to Can I Use to avoid website changes in New browser support. Or just `lch() now works only in Safari`
